<a href="https://colab.research.google.com/github/sivammohapatra1310/Machine-Learning/blob/main/Python-Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# prompt: take input for a number

x = int(input("Enter a number: "))
print(x)
print(x*x)

Enter a number: 10
10
100


In [ ]:
print('Sivam is staring Machine Learning')

Sivam is staring Machine Learning


In [ ]:
True or False

True

In [ ]:
'Sivam'.isalnum()

True

In [ ]:
#lists
type([])
a=['Sivam', 'Mohapatra']
a[0:2]
a[1:2]
a.insert(1, 'Rajguru') #success
a.extend([18, 7])
print(a)

['Sivam', 'Rajguru', 'Mohapatra']


new functions
lst.pop(<x>)
lst.index(x, start, end)
sum(lst) max(lst) min(lst)
lst.count(x)
lst*2

*   List item
*   List item



In [ ]:
set_var={"Sivam", "Mohapatra"}
print(set_var)
set_var.add("King")
set_var.difference(set_var)#doesnt update
set_var.intersection(set_var)
set_var.difference_update(set_var)
print(set_var)


{'Sivam', 'Mohapatra'}
set()


In [ ]:
dic={1:"sivam", 2:"mohapatra"}
for x in dic:
  print(x, dic[x])
print()
for x in dic.values():
  print(x)
for x in dic.items():
  print(x)
dic[3]="king"
print(dic)
dic[3]={3:"maharaja"}
print(dic[3][3])

1 sivam
2 mohapatra

sivam
mohapatra
(1, 'sivam')
(2, 'mohapatra')
{1: 'sivam', 2: 'mohapatra', 3: 'king'}
maharaja


In [ ]:
#tuple values can't be changed
ytup=("Sivam", "mohapatra")
print(ytup);
ytup.count("mohapatra")
ytup.index("mohapatra")

('Sivam', 'mohapatra')


1

# **NUMPY**

In [2]:
import numpy as np

In [3]:
lst=[1,2,3,4,5]
arr=np.array(lst)
print(type(arr))
print(arr)
print(arr.shape)#dimensions
arr=np.array([lst, lst]);
print(type(arr))
print(arr)
print(arr.shape)#dimensions
print(np.version)

<class 'numpy.ndarray'>
[1 2 3 4 5]
(5,)
<class 'numpy.ndarray'>
[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)
<module 'numpy.version' from '/usr/local/lib/python3.10/dist-packages/numpy/version.py'>


In [2]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
print('2nd element on 2nd row: ', arr[1][1])

print('Last element on 1st row: ', arr[0][-1])

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[-3:-1])
print()
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4:2])
print(arr[0:2, 2])

2nd element on 1st row:  2
2nd element on 2nd row:  7
Last element on 1st row:  5
[2 3 4 5]
[5 6]

[7 9]
[3 8]


In [3]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
arr[0] = 42
y[1]=90
print(arr)
print(x)
print(y)
print(x.base)
print(y.base)

[42 90  3  4  5]
[1 2 3 4 5]
[42 90  3  4  5]
None
[42 90  3  4  5]


In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4))

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1) #for flattening the array

print(newarr)

[[1 2 3 4]
 [5 6 7 8]]


In [2]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

for idx, x in np.ndenumerate(arr):
  print(idx, x)

1
2
3
4
5
6
7
8
(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8


In [12]:
import numpy as np
arr= np.array([1,2,2,3])
print(arr<=1)
print(arr*2)
print(arr[arr<3])
print(np.ones(4, dtype=int))
print(np.random.rand(3, 3))
print(np.random.randn(3, 3))
print(np.random.randint(1, 1000, 10))

print()

arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[ True False False False]
[2 4 4 6]
[1 2 2]
[1 1 1 1]
[[0.26045501 0.94327342 0.21790419]
 [0.47762713 0.32803504 0.40625526]
 [0.89543982 0.81978391 0.43600552]]
[[ 0.01052809 -1.06361562 -0.31739772]
 [-0.20717866  0.71007086  0.1439829 ]
 [ 0.74549306  1.17890899 -0.76613182]]
[712 359 247 568 407 683 101 946 411 258]

[False False  True  True]
[43 44]


In [23]:
from numpy import random as r
print(r.randint(200), r.rand()*200 )
x = r.randint(100, size=(3, 5))
print(x)
print()

x = r.rand(5)
print(x)

63 192.8455550571601
[[ 6 18 65 84 23]
 [24 24 11 15 85]
 [37  1  4 52 92]]

[0.06683727 0.77697366 0.67224156 0.88975985 0.14917386]


***PANDAS***


In [3]:
import pandas as pd
# pd.DataFrame(np.arange)
a = [1, 7, 2]
myvar = pd.Series(a)
print(myvar)
print()
myvar = pd.Series(a, index = ["x", "y", "z"])
print(myvar)
print()
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)
print()
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories, index = ["day1", "day2"]) #creating from only a part of the set
print(myvar)
print()



0    1
1    7
2    2
dtype: int64

x    1
y    7
z    2
dtype: int64

day1    420
day2    380
day3    390
dtype: int64

day1    420
day2    380
dtype: int64



DATAFRAMES

In [5]:
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

print(df)
print()
print(df.loc["day2"])
print()
print(df.loc[["day1", "day2"]]) #returns a Panda series
df=pd.read_csv('First.csv')
print(to_string(df))

      calories  duration
day1       420        50
day2       380        40
day3       390        45

calories    380
duration     40
Name: day2, dtype: int64

      calories  duration
day1       420        50
day2       380        40


# ***READING CSV***

In [5]:
!ls
# import pandas as pd
# df = pd.read_csv('data.csv')
# print(df.to_string())

sample_data


In [5]:
import pandas as pd
data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}
df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

df.to_csv('data.csv')
!ls


data.csv  sample_data
